<script type="text/javascript">
pruebasunitarias_ = Array(
    //id_programa
    Array(1,'id_programa',1,'',false),
    Array(1,'id_programa',2,'31',true),
    Array(2,'id_programa',3,'11111111',false),
    Array(2,'id_programa',4,'31',true),
    Array(3,'id_programa',5,'a',false),
    Array(3,'id_programa',6,'31',true),
    Array(4,'id_programa',7,'a',false),
    Array(4,'id_programa',8,'31',true),

    //nombre_programa
    Array(1,'nombre_programa',9,'al',false),
    Array(1,'nombre_programa',10,'Prueba Programa ñ',true),
    Array(2,'nombre_programa',11,'ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',false),
    Array(2,'nombre_programa',12,'Prueba Programa ñ',true),
    Array(3,'nombre_programa',13,'22555599',false),
    Array(3,'nombre_programa',14,'Prueba Programa ñ',true),
    Array(4,'nombre_programa',15,'%',false),
    Array(4,'nombre_programa',16,'Prueba Programa ñ',true),
    Array(5,'nombre_programa',17,'%',false),
    Array(5,'nombre_programa',18,'Prueba Programa ñ',true),

    //acronimo_programa
    Array(1,'acronimo_programa',19,'a',false),
    Array(1,'acronimo_programa',20,'acronimo',true),
    Array(2,'acronimo_programa',21,'aaaaaaaaaaaaaaaaaaaaaaaaa',false),
    Array(2,'acronimo_programa',22,'acronimo',true),
    Array(3,'acronimo_programa',23,'31124',false),
    Array(3,'acronimo_programa',24,'acronimo',true),
    Array(4,'acronimo_programa',25,'acronimó',false),
    Array(4,'acronimo_programa',26,'acronimo',true),
    Array(5,'acronimo_programa',27,'pr ograma',false),
    Array(5,'acronimo_programa',28,'acronimo',true),
    Array(6,'acronimo_programa',29,'pr ograma',false),
    Array(6,'acronimo_programa',30,'acronimo',true),

    //nombre_original_programa
    Array(1,'nombre_original_programa',31,'a',false),
    Array(1,'nombre_original_programa',32,'programa original ñ',true),
    Array(2,'nombre_original_programa',33,'ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',false),
    Array(2,'nombre_original_programa',34,'programa original ñ',true),
    Array(3,'nombre_original_programa',35,'1234567',false),
    Array(3,'nombre_original_programa',36,'programa original ñ',true),
    Array(4,'nombre_original_programa',37,'&',false),
    Array(4,'nombre_original_programa',38,'programa original ñ',true),
    Array(5,'nombre_original_programa',39,'&',false),
    Array(5,'nombre_original_programa',40,'programa original ñ',true),

    //autor_programa
    Array(1,'autor_programa',41,'a',false),
    Array(1,'autor_programa',42,'Álfabetico ñ',true),
    Array(2,'autor_programa',43,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',false),
    Array(2,'autor_programa',44,'Álfabetico ñ',true),
    Array(3,'autor_programa',45,'7531522',false),
    Array(3,'autor_programa',46,'Álfabetico ñ',true),
    Array(4,'autor_programa',47,'&',false),
    Array(4,'autor_programa',48,'Álfabetico ñ',true),
    Array(5,'autor_programa',49,'7531522',false),
    Array(5,'autor_programa',50,'Álfabetico ñ',true),

    //autor_original_programa
    Array(1,'autor_original_programa',51,'a',false),
    Array(1,'autor_original_programa',52,'Álfabetico ñ',true),
    Array(2,'autor_original_programa',53,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',false),
    Array(2,'autor_original_programa',54,'Álfabetico ñ',true),
    Array(3,'autor_original_programa',55,'7531522',false),
    Array(3,'autor_original_programa',56,'Álfabetico ñ',true),
    Array(4,'autor_original_programa',57,'&',false),
    Array(4,'autor_original_programa',58,'Álfabetico ñ',true),
    Array(5,'autor_original_programa',59,'&',false),
    Array(5,'autor_original_programa',60,'Álfabetico ñ',true),

    //ano_programa
    Array(1,'ano_programa',61,'12',false),
    Array(1,'ano_programa',62,'2015',true),
    Array(2,'ano_programa',63,'12344',false),
    Array(2,'ano_programa',64,'2015',true),
    Array(3,'ano_programa',65,'hola',false),
    Array(3,'ano_programa',66,'2015',true),
    Array(4,'ano_programa',67,'2999',false),
    Array(4,'ano_programa',68,'2015',true),
    Array(5,'ano_programa',69,'2999',false),
    Array(5,'ano_programa',70,'2015',true),

    //ano_original_programa
    Array(1,'ano_original_programa',71,'12',false),
    Array(1,'ano_original_programa',72,'2015',true),
    Array(2,'ano_original_programa',73,'12344',false),
    Array(2,'ano_original_programa',74,'2015',true),
    Array(3,'ano_original_programa',75,'hola',false),
    Array(3,'ano_original_programa',76,'2015',true),
    Array(4,'ano_original_programa',77,'2999',false),
    Array(4,'ano_original_programa',78,'2015',true),
    Array(5,'ano_original_programa',79,'2999',false),
    Array(5,'ano_original_programa',80,'2015',true),

    //requisitos_programa
    Array(1,'requisitos_programa',81,'a',false),
    Array(1,'requisitos_programa',82,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmód teñpor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',true),
    Array(2,'requisitos_programa',83,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',false),
    Array(2,'requisitos_programa',84,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmód teñpor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',true),
    Array(3,'requisitos_program',85,'123456',false),
    Array(3,'requisitos_programa',86,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmód teñpor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',true),
    Array(4,'requisitos_programa',87,'$',false),
    Array(4,'requisitos_programa',88,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmód teñpor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',true),
    Array(5,'requisitos_programa',89,'$',false),
    Array(5,'requisitos_programa',90,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmód teñpor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',true),

    //poblacion_desde_programa
    Array(1,'poblacion_desde_programa',91,'',false),
    Array(1,'poblacion_desde_programa',92,'22',true),
    Array(2,'poblacion_desde_programa',93,'111',false),
    Array(2,'poblacion_desde_programa',94,'22',true),
    Array(3,'poblacion_desde_programa',95,'aa',false),
    Array(3,'poblacion_desde_programa',96,'22',true),
    Array(4,'poblacion_desde_programa',97,'aa',false),
    Array(4,'poblacion_desde_programa',98,'22',true),

    //poblacion_hasta_programa
    Array(1,'poblacion_hasta_programa',99,'',false),
    Array(1,'poblacion_hasta_programa',100,'22',true),
    Array(2,'poblacion_hasta_programa',101,'111',false),
    Array(2,'poblacion_hasta_programa',102,'22',true),
    Array(3,'poblacion_hasta_programa',103,'aa',false),
    Array(3,'poblacion_hasta_programa',104,'22',true),
    Array(4,'poblacion_hasta_programa',105,'aa',false),
    Array(4,'poblacion_hasta_programa',106,'22',true),

    //unidad_poblacion
    Array(1,'unidad_poblacion',107,'EJEMPLO',false),
    Array(1,'unidad_poblacion',108,'MESES',true),
    Array(1,'unidad_poblacion',109,'AÑOS',true),
    Array(2,'unidad_poblacion',110,'EJEMPLO',false),
    Array(2,'unidad_poblacion',111,'MESES',true),
    Array(2,'unidad_poblacion',112,'AÑOS',true),

    //tipo_programa
    Array(1,'tipo_programa',113,'EJEMPLO',false),
    Array(1,'tipo_programa',114,'EVALUACIÓN',true),
    Array(1,'tipo_programa',115,'INTERVENCIÓN',true),
    Array(1,'tipo_programa',116,'EVALUACIÓN E INTERVENCIÓN',true),
    Array(2,'tipo_programa',117,'EJEMPLO',false),
    Array(2,'tipo_programa',118,'EVALUACIÓN',true),
    Array(2,'tipo_programa',119,'INTERVENCIÓN',true),
    Array(2,'tipo_programa',120,'EVALUACIÓN E INTERVENCIÓN',true),

    //tiempo_aplicacion_programa
    Array(1,'tiempo_aplicacion_programa',121,'',false),
    Array(1,'tiempo_aplicacion_programa',122,'123',true),
    Array(2,'tiempo_aplicacion_programa',123,'12345',false),
    Array(2,'tiempo_aplicacion_programa',124,'123',true),
    Array(3,'tiempo_aplicacion_programa',125,'aaa',false),
    Array(3,'tiempo_aplicacion_programa',126,'123',true),
    Array(4,'tiempo_aplicacion_programa',127,'aaa',false),
    Array(4,'tiempo_aplicacion_programa',128,'123',true),

    //descrip_interp_programa
    Array(1,'descrip_interp_programa',129,'Descripcion',false),
    Array(1,'descrip_interp_programa',130,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmód teñpor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',true),
    Array(2,'descrip_interp_programa',131,'[mas de 5000 caracteres]',false),
    Array(2,'descrip_interp_programa',132,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmód teñpor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',true),   
    Array(3,'descrip_interp_programa',133,'24634684642534524534543432124879897846545312324154365261246124621465621412464313421376316431343141101',false),
    Array(3,'descrip_interp_programa',134,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmód teñpor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',true),    
    Array(4,'descrip_interp_programa',135,'&',false),
    Array(4,'descrip_interp_programa',136,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmód teñpor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',true),    
    Array(5,'descrip_interp_programa',137,'&',false),
    Array(5,'descrip_interp_programa',138,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmód teñpor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',true),

    //fichero_programa
    Array(1,'fichero_programa',139,'a',false),
    Array(1,'fichero_programa',140,'ejemplodearchivo',true),
    Array(2,'fichero_programa',141,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',false),
    Array(2,'fichero_programa',142,'ejemplodearchivo',true), 
    Array(3,'fichero_programa',143,'áááaaaáááááááaaaáaá',false),
    Array(3,'fichero_programa',144,'ejemplodearchivo',true),   
    Array(4,'fichero_programa',145,'ññññññññññññyaaaa',false),
    Array(4,'fichero_programa',146,'ejemplodearchivo',true),   
    Array(5,'fichero_programa',147,'asadasd asdasdas',false),
    Array(5,'fichero_programa',148,'ejemplodearchivo',true),
    Array(6,'fichero_programa',149,'asadasd asdasdas',false),
    Array(6,'fichero_programa',150,'ejemplodearchivo',true),

    //enlace_programa
    Array(1,'enlace_programa',151,'a',false),
    Array(1,'enlace_programa',152,'aaaaa://.:////:aaaaaaaa.',true),
    Array(2,'enlace_programa',153,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',false),
    Array(2,'enlace_programa',154,'aaaaa://.:////:aaaaaaaa.',true),
    Array(3,'enlace_programa',155,'á',false),
    Array(3,'enlace_programa',156,'aaaaa://.:////:aaaaaaaa.',true),
    Array(4,'enlace_programa',157,'ñ',false),
    Array(4,'enlace_programa',158,'aaaaa://.:////:aaaaaaaa.',true),
    Array(5,'enlace_programa',159,'asdklas asdasdasd',false),
    Array(5,'enlace_programa',160,'aaaaa://.:////:aaaaaaaa.',true),
    Array(6,'enlace_programa',161,'&',false),
    Array(6,'enlace_programa',162,'aaaaa://.:////:aaaaaaaa.',true),
    Array(7,'enlace_programa',163,'&',false),
    Array(7,'enlace_programa',164,'aaaaa://.:////:aaaaaaaa.',true),

    //formato_programa
    Array(1,'formato_programa',165,'EJEMPLO',false),
    Array(1,'formato_programa',166,'PAPEL',true),
    Array(1,'formato_programa',167,'ELECTRONICO',true),
    Array(1,'formato_programa',168,'PAPEL Y ELECTRONICO',true),
    Array(2,'formato_programa',169,'EJEMPLO',false),
    Array(2,'formato_programa',170,'PAPEL',true),
    Array(2,'formato_programa',171,'ELECTRONICO',true),
    Array(2,'formato_programa',172,'PAPEL Y ELECTRONICO',true),

    //modo_correccion_programa
    Array(1,'modo_correccion_programa',173,'EJEMPLO',false),
    Array(1,'modo_correccion_programa',174,'PAPEL',true),
    Array(1,'modo_correccion_programa',175,'ELECTRONICO',true),
    Array(1,'modo_correccion_programa',176,'PAPEL Y ELECTRONICO',true),
    Array(2,'modo_correccion_programa',177,'EJEMPLO',false),
    Array(2,'modo_correccion_programa',178,'PAPEL',true),
    Array(2,'modo_correccion_programa',179,'ELECTRONICO',true),
    Array(2,'modo_correccion_programa',180,'PAPEL Y ELECTRONICO',true),

    //modo_aplicacion_programa
    Array(1,'modo_aplicacion_programa',181,'EJEMPLO',false),
    Array(1,'modo_aplicacion_programa',182,'INDIVIDUAL',true),
    Array(1,'modo_aplicacion_programa',183,'COLECTIVO',true),
    Array(1,'modo_aplicacion_programa',184,'INDIVIDUAL Y COLECTIVO',true),
    Array(2,'modo_aplicacion_programa',185,'EJEMPLO',false),
    Array(2,'modo_aplicacion_programa',186,'INDIVIDUAL',true),
    Array(2,'modo_aplicacion_programa',187,'COLECTIVO',true),
    Array(2,'modo_aplicacion_programa',188,'INDIVIDUAL Y COLECTIVO',true),

    //imagen_programa
    Array(1,'imagen_programa',189,'aaa',false),
    Array(1,'imagen_programa',190,'asdasdasdsadasdasd',true),
    Array(2,'imagen_programa',191,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',false),
    Array(2,'imagen_programa',192,'asdasdasdsadasdasd',true),
    Array(3,'imagen_programa',193,'áaaaaáaaáááááááaaaaáááa',false),
    Array(3,'imagen_programa',194,'asdasdasdsadasdasd',true),
    Array(4,'imagen_programa',195,'ñññññññññññññññaaaaaaaa',false),
    Array(4,'imagen_programa',196,'asdasdasdsadasdasd',true),
    Array(5,'imagen_programa',197,'aaaaaaaa aaaaaaaaa',false),
    Array(5,'imagen_programa',198,'asdasdasdsadasdasd',true),
    Array(6,'imagen_programa',199,'aaaaaaaa aaaaaaaaa',false),
    Array(6,'imagen_programa',200,'asdasdasdsadasdasd',true),
);
</script> 